#!/usr/bin/env bash
# This parses Apache log files a in list format.
#  and groups visitors by IP and HTTP status code.
#  then displays the number of occurrences, IP, and HTTP status
#  with code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
