#!/usr/bin/env bash
# To display 'Best School' 10 times, but @9th time say 'Hi',then@10th'Best School'

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
