#!/usr/bin/env bash
# This will display numbers from 1 to 20 and include the following:
#   "bad luck from China" @ the 4th iteration
#   "bad luck from Japan" @ the 9th iteration
#   "bad luck from Italy" @ the 17th loop iteration

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
