#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic

sudo apt-get update                                  # Update the package list on the system
sudo apt-get install ufw                             # Install the ufw package
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw   # Enable IPv6 support
sudo ufw default deny incoming                       # Set default policy for incoming traffic to "deny"
sudo ufw default allow outgoing                      # Set default policy for outgoing traffic to "allow"
sudo ufw allow 22/tcp                                # Allow incoming traffic on TCP port 22 (SSH)
sudo ufw allow 443/tcp                               # Allow incoming traffic on TCP port 443 (HTTPS)
sudo ufw allow 80/tcp                                # Allow incoming traffic on TCP port 80 (HTTP)
sudo ufw disable                                     # Disable ufw to start with a clean slate
sudo ufw enable                                      # Enable ufw firewall
